/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imc2024;

/**
 *
 * @author 2830482311024
 */
public class IMC extends javax.swing.JFrame {

    /**
     * Creates new form IMC
     */
    public IMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel_title = new javax.swing.JLabel();
        jLabel_lenght = new javax.swing.JLabel();
        jTextField_lenght = new javax.swing.JTextField();
        jLabel_weight = new javax.swing.JLabel();
        jTextField_weight = new javax.swing.JTextField();
        jButton_calculateIMC = new javax.swing.JButton();
        jTextField_result = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabel_title.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        JLabel_title.setText("CALCULO DO IMC");

        jLabel_lenght.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_lenght.setText("Minha altura é: ");

        jTextField_lenght.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel_weight.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_weight.setText("Meu peso é: ");

        jTextField_weight.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_weightActionPerformed(evt);
            }
        });

        jButton_calculateIMC.setBackground(new java.awt.Color(0, 0, 255));
        jButton_calculateIMC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_calculateIMC.setForeground(new java.awt.Color(255, 255, 0));
        jButton_calculateIMC.setText("Calcular IMC");
        jButton_calculateIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calculateIMCActionPerformed(evt);
            }
        });

        jTextField_result.setEditable(false);
        jTextField_result.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_resultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_result, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel_weight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_lenght, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_lenght, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(jButton_calculateIMC)))
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(JLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_lenght, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_lenght, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton_calculateIMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jTextField_result, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_weightActionPerformed

    private void jButton_calculateIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calculateIMCActionPerformed
        // TODO add your handling code here:
        float lenght = Float.valueOf(jTextField_lenght.getText());
        float weight = Float.valueOf(jTextField_weight.getText());
        String imc = String.valueOf(weight / (lenght * lenght));
        String var = "";
        
        if (Float.valueOf(imc) < 18.5f)
            var = "MAGRO!";
        else if (Float.valueOf(imc) < 24.9f)
            var = "NORMAL!";
        else if (Float.valueOf(imc) < 29.9f)
            var = "OBESIDADE I!";
        else if (Float.valueOf(imc) < 39.9f)
            var = "OBESIDADE II!";
        else if (Float.valueOf(imc) > 40.0f)
            var = "OBESIDADE III!";
        
        jTextField_result.setText("Seu IMC é de " + imc + " - " + var);
    }//GEN-LAST:event_jButton_calculateIMCActionPerformed

    private void jTextField_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_resultActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_title;
    private javax.swing.JButton jButton_calculateIMC;
    private javax.swing.JLabel jLabel_lenght;
    private javax.swing.JLabel jLabel_weight;
    private javax.swing.JTextField jTextField_lenght;
    private javax.swing.JTextField jTextField_result;
    private javax.swing.JTextField jTextField_weight;
    // End of variables declaration//GEN-END:variables
}
